### ISSUE TITLE
Amazon Alexa Skill - Feature Request

### ISSUE THREAD

**Issue by AppleEducate** [Gamadril/hyperion-remote#4]
Do you think it is possible to make an amazon Alexa Skill that runs on a web service like you have made here?

**Comment by Gamadril** [comment]
I think you are asking if it's possible to integrate hyperion with Alexa. Actually hyperion-remote is not providing any web services it just uses WebSockets instead of TCP-Sockets to communicate with hyperion for controlling it over the local network. Alexa integration has to be done in hyperion itself, because if I understand the Alexa infrastructure right, all devices has to be connected to a cloud and Alexa will communicate only to that cloud which will route the requests to the right device.

**Comment by AppleEducate** [comment]
Thanks for the info!
